/** Shared by the browser and authoritative server. Distances are tiles; times are seconds. */
const baseHealth = 100;

export const gameConfig = {
  maps: { defaultId: "greenwood" },
  match: {
    duration: 300,
    mvp: { killWeight: 100, damageWeight: 0.1, deathPenalty: 25, celebrationDuration: 3 },
    winningGemCount: 10,
    victoryCountdown: 15,
    gemSpawnInterval: 4,
    gemCap: 15,
    pickupRadius: 0.65,
    respawnDelay: 5,
    restartDelay: 8,
    maxPlayers: 64,
    teamSize: 3,
    dummyHealth: 1000,
    gemBatchMin: 1,
    gemBatchMax: 4,
    gemScatterRadius: 4,
    gemDespawnTime: 5,
  },
  player: {
    baseHealth,
    respawnInvulnerability: 2,
    moveSpeed: 5.25,
    regenerationDelay: 3,
    regenerationPerSecond: 0,
    hitRadius: 0.38,
    collisionStep: 0.1,
    hpSmoothing: 12,
  },
  skills: {
    basic: { cooldown: 0.45, projectileSpeed: 13, collisionStep: 0.15, range: 9, damage: 22 },
    dash: { cooldown: 4, distance: 3, speed: 17 },
    ultimate: {
      cooldown: 10,
      radius: 2.4,
      range: 7,
      damage: baseHealth * 0.45,
      windup: 1,
      animationSpeed: 1,
      duration: 1.2,
      knockbackDistance: 2,
      knockbackSpeed: 9,
    },
  },
  vfx: {
    dashSmoke: { maxPuffs: 96, lifetime: 0.65, interval: 0.035, size: 0.28, rise: 0.5, color: "#edf0ea" },
    muzzleLifetime: 0.12,
    muzzleLength: 0.4,
    damageTextPopTime: 0.2,
    sparkGravity: 7,
    beamLength: 1.35,
    beamWidth: 0.12,
    beamCore: "#ffffff",
    beamGlow: "#fff5a8",
    sparkColors: ["#ffffff", "#ff62bd"],
    sparksPerImpact: 14,
    sparkLifetime: 0.42,
    sparkSpeed: 3.8,
    maxSparks: 280,
    damageTextLifetime: 0.8,
    damageTextRise: 1.2,
    damageTextPop: 0.35,
    explosion: {
      frameSize: 192,
      frameCount: 36,
      core: "#fffde5",
      light: "#ffe674",
      orange: "#ff9d17",
      amber: "#e86712",
      smoke: "#402040",
      edge: "#281632",
    },
  },
  bot: { moveSpeed: 2.4, attackInterval: 1.4 },
  audio: {
    files: {
      basic: "/sounds/basic.wav",
      dash: "/sounds/dash.wav",
      ultimate: "/sounds/ultimate.wav",
    },
    hurt: {duration:0.32,frequency:190,endFrequency:95,volume:0.38,formant:800},
    combo2: {duration:0.28,frequency:523,endFrequency:784,volume:0.3},
    combo3: {duration:0.34,frequency:659,endFrequency:988,volume:0.34},
    combo4: {duration:0.4,frequency:784,endFrequency:1175,volume:0.38},
    combo5: {duration:0.5,frequency:1047,endFrequency:1568,volume:0.42},
    masterVolume: 0.45,
    ambientVolume: 0.025,
    maxVoices: 24,
    audibleRadius: 18,
    basic: { duration: 0.16, frequency: 1150, endFrequency: 260, volume: 0.16 },
    dash: { duration: 0.28, frequency: 1900, endFrequency: 300, volume: 0.24 },
    ultimate: { duration: 0.95, frequency: 150, endFrequency: 38, volume: 0.5 },
  },
  network: {
    tickRate: 30,
    inputInterval: 0.08,
    inputTimeout: 0.35,
    port: 3001,
  },
  teams: [
    { name: "Fern", color: "#3eaa89" },
    { name: "Coral", color: "#ee7866" },
  ],
};
