import './style.css';
import * as THREE from 'three';
import {createWorld,SIZE,START} from './world.js';
import {buildTerrain} from './terrain.js';
import {Player} from './player.js';
const host=document.querySelector('#world');
const world=createWorld();
const scene=new THREE.Scene();scene.background=new THREE.Color('#dce8c9');
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Greenwood landscape. Use WASD or arrow keys to move.');
const camera=new THREE.OrthographicCamera();const target=new THREE.Vector3(22,0,23);const offset=new THREE.Vector3(25,30,25);scene.add(new THREE.HemisphereLight(0xffffe5,0x6d8d64,1.5));const sun=new THREE.DirectionalLight(0xfff5d4,2.5);sun.position.set(-12,32,-8);sun.target.position.set(22,0,22);scene.add(sun,sun.target);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35,near:.1,far:100});sun.shadow.bias=-.0005;sun.shadow.normalBias=.025;buildTerrain(scene,world);
const map=document.querySelector('#minimap'),ctx=map.getContext('2d');const visited=new Set();let steps=0;function updateMap(tile){ctx.clearRect(0,0,160,160);const s=160/SIZE;for(const t of world.tiles){ctx.fillStyle=t.water?'#71bbc0':t.tree?'#61854e':t.sand?'#bdc58b':'#a7bc87';ctx.fillRect(t.x*s,t.z*s,s+.3,s+.3)}ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.fillStyle='#ec7256';ctx.beginPath();ctx.arc(tile.x*s+s/2,tile.z*s+s/2,3.7,0,Math.PI*2);ctx.fill();ctx.stroke();document.querySelector('#coords').textContent=`${String(tile.x).padStart(2,'0')}, ${String(tile.z).padStart(2,'0')}`;}
const player=new Player(scene,world,tile=>{visited.add(`${tile.x},${tile.z}`);steps++;updateMap(tile);document.querySelector('#explored').textContent=`${visited.size} tiles discovered · Keep wandering`});updateMap(START);
const ring=new THREE.Mesh(new THREE.RingGeometry(.43,.47,4),new THREE.MeshBasicMaterial({color:0xfff3bf,side:THREE.DoubleSide,transparent:true,opacity:.8}));ring.rotation.set(-Math.PI/2,0,Math.PI/4);scene.add(ring);
function resize(){const w=host.clientWidth,h=host.clientHeight;const span=w<760?17:23;camera.left=-span*w/h/2;camera.right=span*w/h/2;camera.top=span/2;camera.bottom=-span/2;camera.near=.1;camera.far=150;camera.updateProjectionMatrix();renderer.setSize(w,h)}window.addEventListener('resize',resize);resize();
const directions={w:[0,-1],ArrowUp:[0,-1],s:[0,1],ArrowDown:[0,1],a:[-1,0],ArrowLeft:[-1,0],d:[1,0],ArrowRight:[1,0]};const held=new Set();const dialog=document.querySelector('dialog');window.addEventListener('keydown',e=>{if(directions[e.key]&&!dialog.open&&!['BUTTON','INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();held.add(e.key);if(!e.repeat)player.move(...directions[e.key])}});window.addEventListener('keyup',e=>held.delete(e.key));window.addEventListener('blur',()=>held.clear());document.addEventListener('visibilitychange',()=>held.clear());
const touch={up:'w',down:'s',left:'a',right:'d'};document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{b.setPointerCapture(e.pointerId);held.add(touch[b.dataset.dir])});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>held.delete(touch[b.dataset.dir]))});
let toastTimer;function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2600)}
document.querySelector('#help').onclick=()=>{held.clear();dialog.showModal()};dialog.querySelectorAll('button').forEach(b=>b.onclick=()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('#reset').onclick=()=>{player.reset();held.clear();toast('Back to your little starting place.')};document.querySelector('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Fullscreen isn’t available in this browser.')}};
const menu=document.querySelector('#character-menu');document.querySelector('#character').setAttribute('aria-expanded','false');document.querySelector('#character').onclick=()=>{menu.hidden=!menu.hidden;document.querySelector('#character').setAttribute('aria-expanded',String(!menu.hidden))};document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{const skin=b.dataset.avatar;player.setSkin(skin);document.querySelector('#character').innerHTML=`${skin==='pip'?'Pip':'Sprout'} <span>⌄</span>`;document.querySelector('.avatar-icon').classList.toggle('sprout',skin==='sprout');menu.hidden=true;document.querySelector('#character').setAttribute('aria-expanded','false');b.blur();toast(skin==='pip'?'Pip is ready to wander.':'A fresh adventure with Sprout.')});document.addEventListener('pointerdown',e=>{if(!e.target.closest('.character-select')){menu.hidden=true;document.querySelector('#character').setAttribute('aria-expanded','false')}});
let audio;document.querySelector('#sound').onclick=async()=>{try{if(!audio){audio=new AudioContext();const buffer=audio.createBuffer(1,audio.sampleRate*4,audio.sampleRate);const data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+(Math.random()*2-1)*.025)/1.025;data[i]=last*3}const source=audio.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=700;const gain=audio.createGain();gain.gain.value=.17;source.connect(filter).connect(gain).connect(audio.destination);source.start();}else if(audio.state==='running'){await audio.suspend()}else await audio.resume();const active=audio.state==='running';document.querySelector('#sound').classList.toggle('active',active);document.querySelector('#sound').setAttribute('aria-label',active?'Mute ambient sound':'Enable ambient sound');toast(active?'A little riverside ambience.':'Ambient sound off.')}catch{toast('Audio isn’t available in this browser.')}};
const clock=new THREE.Clock();let time=0;function animate(){const dt=Math.min(clock.getDelta(),.05);time+=dt;if(!dialog.open){const key=[...held].at(-1);if(key)player.move(...directions[key]);player.update(dt,time)}target.lerp(new THREE.Vector3(player.group.position.x-1.3,0,player.group.position.z-1.3),1-Math.exp(-dt*2));camera.position.copy(target).add(offset);camera.lookAt(target);ring.position.set(player.group.position.x,.027,player.group.position.z);renderer.render(scene,camera)}renderer.setAnimationLoop(animate);document.querySelector('#loading').remove();
